### ISSUE TITLE
aggregate by hand vs open_mfdataset?

### ISSUE THREAD

**Issue by jerabaul29** [knutfrode/concepts#2]
With reference to https://github.com/knutfrode/concepts/blob/main/Open_MFDataset_overlap.ipynb : any reason for doing this "by hand" rather than natively in xarray with open_mfdataset? :)

https://docs.xarray.dev/en/stable/generated/xarray.open_mfdataset.html

**Comment by knutfrode** [comment]
These datasets are overlapping, which is typically the case with forecast archives. So this small method opens each dataset, and selects the first X (non-overlapping) hours, and thereafter merges them. 

open_mfdataset does not handle overlapping files, but it would be nice if it would some day.

Eventually we would like to use this trick, to not open each single URL until it is really needed:
https://climate-cms.org/posts/2018-09-14-dask-era-interim.html

**Comment by jerabaul29** [comment]
Aaaah, thanks for the explanation :) . I was thinking about 'our' cache case when reading this, which is why I was confused, but makes very good sense. Thanks :) .
